package proyecto;

import java.awt.Color;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 18PROGB0269
 */
public class definicion extends javax.swing.JFrame {

    /**
     * Creates new form definicion
     */
    public definicion() {
        initComponents();
        this.getContentPane().setBackground(Color.DARK_GRAY);
         this.setDefaultCloseOperation(menu.DO_NOTHING_ON_CLOSE);
        this.setIconImage(new ImageIcon (getClass().getResource("/imagenes/logo.jpg")).getImage());
         this.setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtContenido = new javax.swing.JTextArea();
        lblDefinicion = new javax.swing.JLabel();
        btnRegresar2 = new javax.swing.JButton();
        lblImagen3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fase Obscura");
        setResizable(false);

        txtContenido.setEditable(false);
        txtContenido.setColumns(20);
        txtContenido.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        txtContenido.setLineWrap(true);
        txtContenido.setRows(5);
        txtContenido.setText("La fase oscura, también conocida como biocinética o estimulatoria, es la segunda\nfase del proceso de fotosíntesis. En esta etapa se producen un cumulo de\nreacciones que no necesitan de la luz solar y que convierten el dióxido de\ncarbono, entre otros compuestos, en azucares. Hay que señalar que, aunque la\nfase oscura en las plantas de marihuana y en las demás, no necesita la luz solar\nde forma directa, si que está regulada de forma indirecta por la misma. Esto se\ndebe a que algunas enzimas implicadas en el proceso de asimilación del carbono\nsí que dependen de la luz solar.\nDe forma esquematizada, hay que señalar que las plantas absorben el CO2\ndel\naire mediante los estromas de las hojas. A continuación, dentro del estroma del\ncloroplasto se reduce el carbono de forma cíclica, proceso conocido como el Ciclo\nde Calvin. Para producir estas reacciones, las pantas obtienen los productos de la\nfase luminosa, ATP y NADPH.\nLa fase oscura se divide en dos: la fijación del carbono y el Ciclo de Calvin.");
        txtContenido.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtContenido);

        lblDefinicion.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblDefinicion.setForeground(new java.awt.Color(255, 255, 255));
        lblDefinicion.setText("Definición");

        btnRegresar2.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        btnRegresar2.setForeground(new java.awt.Color(102, 0, 102));
        btnRegresar2.setText("Regresar");
        btnRegresar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar2ActionPerformed(evt);
            }
        });

        lblImagen3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagen3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagen030.jpg"))); // NOI18N
        lblImagen3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(lblDefinicion)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegresar2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(lblImagen3, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblDefinicion)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImagen3, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegresar2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar2ActionPerformed
    dispose ();
    }//GEN-LAST:event_btnRegresar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(definicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(definicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(definicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(definicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new definicion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDefinicion;
    private javax.swing.JLabel lblImagen3;
    private javax.swing.JTextArea txtContenido;
    // End of variables declaration//GEN-END:variables
}
